# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: flightctl-acm-addon
  name: configmap-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configmap
  namespace: flightctl-acm-addon
subjects:
- kind: ServiceAccount
  name: default
  namespace: flightctl-acm-addon
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
